### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by deshack** [SqueezyWeb/KISS#1]
- [ ] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/SqueezyWeb/KYSS/issues)

---

**What is the current behavior?**

Currently users are able to authenticate and register, but don't have particular permissions. Laravel allows [protecting routes](https://laravel.com/docs/master/authentication#protecting-routes), but misses of a strong permission-based user management.

**What is the expected or desired behavior?**

Users should have different roles, each with different (and multiple) permissions to access application contents and features.

[Requirements](https://github.com/SqueezyWeb/KYSS/wiki/Version-0.1-Project-Requirements#requirements) 4 to 7 describe the desired behavior.
