### ISSUE TITLE
Public homepage

### ISSUE THREAD

**Issue by deshack** [SqueezyWeb/KISS#6]
- [ ] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/SqueezyWeb/KYSS/issues)

---

**What is the current behavior?**

Currently KYSS has a very minimal public homepage.

**What is the expected or desired behavior?**

There should be a customizable homepage which provides informations about the company, organization, etc.
