### ISSUE TITLE
Administration area

### ISSUE THREAD

**Issue by deshack** [SqueezyWeb/KISS#8]
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/SqueezyWeb/KYSS/issues)

---

**What is the current behavior?**

There's no administration area.

**What is the expected or desired behavior?**

An administration area is accessible only to users with a specific permission (see #2 and #3) and allows them to modify application settings.

---
## Feature Request

**Please provide use cases for changing the current behavior:**

See #4 

**Other relevant information:**

X
