### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by deshack** [SqueezyWeb/KISS#9]
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/SqueezyWeb/KYSS/issues)

---

**What is the expected or desired behavior?**

Once logged in, users see a dashboard with a number of widgets. Widgets show data from a various number of sources and can be created by extensions.

---
## Feature Request

**Please provide use cases for changing the current behavior:**

There should be a 
1. dashboard visible to all logged-in users
2. The dashboard should contain a collection of widgets
3. Widgets should have a default permission level to be viewed by users
4. Widgets should be able to define a new permission level to be viewed by users, overriding the default permission level
5. At this stage, widgets' data should be read-only
6. Extensions should be able to add custom widgets

**Other relevant information:**

X
